### ISSUE TITLE
PDF Data Extraction Logic Implementation

### ISSUE THREAD

**Issue by cluelessmonk** [ContriHUB/GobHobs#1]
# 🚀 Feature Request: PDF Data Extraction

### Description
The goal is to implement a PDF data extraction logic within the `implementation/pdfextractor` folder. The user can implement either `extractfrompdf.js` or `extractfrompdf.py` to extract meaningful data from PDFs and save the extracted data in a structured JSON format in the `result` folder inside the `pdfextractor` directory.

### Why is this feature important?
This feature is critical for processing PDF documents into a structured format, which can then be fed into a language model (LLM) for further information extraction and analysis. This would allow for better interaction with and understanding of the content inside the PDFs.

### The Solution I would prefer
The PDF data should be extracted and organized into specific structures like:
- Tables
- Body text
- Image descriptions
- Other relevant sections

Once extracted, this data should be saved into a well-structured JSON file. The JSON format should be flexible enough to allow easy integration with LLMs or other systems for further processing.

### Additional context
The solution could be implemented using `extractfrompdf.js` or `extractfrompdf.py`. The implementation should ensure that the JSON file is saved in the `result` folder inside the `pdfextractor` directory, making the extracted information ready for further consumption.

**Comment by CoderFleet** [comment]
@cluelessmonk Could you please assign this issue to me 
I have requested on contrihub's website

**Comment by Rockyoudead8** [comment]
hey @cluelessmonk Could you please assign this issue to me under hacktoberfest2024
i have done research on this issue and i would be able to deliver the best out of it

**Comment by Aryan10** [comment]
On it. Can this be assigned?

**Comment by cluelessmonk** [comment]
Hey Aryan i would like you to go through the task ..
Since you have requested it before coderfleet , I have assigned this task to you ...
If not completed under the certain time period i would be assigning the task to @CoderFleet

**Comment by Aryan10** [comment]
@cluelessmonk Got it, I will do my best to finish under time.

**Comment by CoderFleet** [comment]
@cluelessmonk But on the contrihub website this is assigned to me 
![image](https://github.com/user-attachments/assets/c54731f9-972f-4693-a250-52b67a6e72d3)

**Comment by Aryan10** [comment]
Strange assigned to me too @CoderFleet 
![image](https://github.com/user-attachments/assets/23c24e07-d02d-4970-9855-2f0fa17dd703)
