### ISSUE TITLE
Record Searching implementation on Exact Match or a Probabilistic Match.

### ISSUE THREAD

**Issue by cluelessmonk** [ContriHUB/GobHobs#2]
# 🚀 Feature Request: Phonerecords Data Search

### Description
The goal is to implement a phonerecords data search functionality within the `phonerecords` folder. The implementation should be done in either `searchrecords.js` or `searchrecords.py`. The CSV file containing the phonerecords will first be saved inside the `samplecsv` folder, and then converted into a JSON format, which will be stored in the `data` folder. The search functionality should enable searching for a specific value in the JSON data, returning both exact matches and like/suggestive matches (for potential spelling mistakes).

### Why is this feature important ?
This feature is important for understanding how data searching is implemented. It teaches techniques such as using tries or other search algorithms to efficiently retrieve exact matches and handle slight errors in search queries, providing like or suggestive matches.

### The solution I'd Prefer
- **CSV to JSON Conversion**: The phonerecords CSV data will first be placed inside the `samplecsv` folder. The system will convert this CSV into a JSON format and store it in the `data` folder.
- **Search Logic**: The search functionality should allow searching by specific fields (e.g., name, title, address). The search query will specify:
  1. Which field to search (e.g., `1` for name, `2` for title, `3` for address).
  2. The keyword to search for.
- **Result Output**:
  - Return two lists:
    1. **Exact Match**: Records where the keyword matches exactly.
    2. **Like/Suggestive Match**: Records where there is a near match (e.g., due to spelling errors).

### Additional context
This feature can be implemented in either `searchrecords.js` or `searchrecords.py`. The focus is on building an efficient search mechanism that can return both exact matches and handle fuzzy searching for records with potential spelling errors.

**Comment by anushkaVerma1007** [comment]
sir please assign this issue to me.

**Comment by cluelessmonk** [comment]
Thanks for your reply . ill want you to go through the readme and then work upon the task.
feel free to ping me regarding any problems.

**Comment by anushkaVerma1007** [comment]
Thank you sir for assigning me the issue ..Now i have started work on it
